#This is a sample help desk bot properties config.
server:
  address: 0.0.0.0
  port : 8090
  display-name: Help Desk Bot
  context-path: /helpdesk-bot
  connection-timeout: 20000

email: helpdesk@symphony.com

claimEntityHeader: "<b>Equities Desk Bot</b>"

idle-ticket:
  message: "has been idle for 60 minutes."
  timeout: 1
  unit: "HOURS"

instructional-ticket:
  message: " to close the ticket upon ticket resolution."
  command: "<mention uid=\"%s\"/> <b>Close</b>"

aiServicePrefix: "@"
aiDefaultPrefix: "/"
closeTicketCommand: "Close"
acceptTicketCommand: "Accept Ticket {Ticket_Id}"
addMemberCommand: "Add Member @{Mention} {Membership_Type}"
createTicketMessage: "Ticket created successfully"
acceptTicketClientSuccessResponse: "You have been connected to an agent."
closeTicketSuccessResponse: "Thank you for contacting us, this session is now over. Any new messages in this chat will be delivered to the JPM Equity Team as a new session."
addMemberAgentSuccessResponse: "New member has been added to the help desk."
addMemberClientSuccessResponse: "Your membership to the help desk has been updated by an agent."
welcomeMessage: "Thanks for contacting the Equity Team at JPM. All messages sent in this chat will be delivered to the JPM Equity Team."
noAgentsMessage: "There are no available agents to attend your ticket right now. Please wait for a moment while we connect you to a new agent."

app-authentication:
  enabled: false
  pod:
    host: ${pod.host}
    port: ${pod.port:443}
  session_auth:
    host: ${session_auth.host}
    port: ${session_auth.port:443}
  filter:
    url-patterns:
      - "/v1/*"